import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Container, Grid, Stack } from '@mui/material'
import Sidebar from '@/components/Sidebar'
import ProductDashboard from '@/components/ProductDashboard/ProductDashboard'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        <Stack flexDirection='row' >
          <Sidebar />


          <ProductDashboard />
          {
            children
          }

        </Stack>
      </body>
    </html>
  )
}
